#Copyright Â© 2017 VMware, Inc. All Rights Reserved.
#SPDX-License-Identifier: MIT
---
services: docker

env:
  - container: "tompscanlan/photon-ansible-base"
    init: /usr/lib/systemd/systemd

  - container: "ansible/ansible:centos7"
    init: /usr/lib/systemd/systemd

  - container: "ansible/ansible:fedora24"
    init: /lib/systemd/systemd

  - container: "ansible/ansible:opensuse42.2"
    init: /usr/lib/systemd/systemd

  - container: "ansible/ansible:ubuntu1604"
    init: /lib/systemd/systemd

  - container: "ansible/ansible:ubuntu1404"
    init: /sbin/init

  - container: "ansible/ansible:ubuntu1204"
    init: /sbin/init

before_install:
  - docker pull ${container}

script:
  - container_id=$(mktemp)
  - docker run -d --privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro -v "$PWD:/etc/ansible/roles/ansible-role-govc" "$container" "$init" > "${container_id}"
  - docker exec "$(cat ${container_id})" bash -c 'pip install -U pip'
  - docker exec "$(cat ${container_id})" bash -c 'pip install ansible'
  - docker exec "$(cat ${container_id})" bash -c 'ansible-playbook /etc/ansible/roles/ansible-role-govc/tests/test.yml --syntax-check'
  - docker exec "$(cat ${container_id})" bash -c 'ansible-playbook /etc/ansible/roles/ansible-role-govc/tests/test.yml'

  - docker kill "$(cat ${container_id})"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
